### PR TITLE
Unpin six also in other requirements file

### PR DESCRIPTION
**Pull request by nsoranzo**
See https://github.com/ISA-tools/isa-rwval/pull/12

Also can we please have a new release on PyPI with the updated requirements?
Thanks!

### CODE REVIEW

**Comment by nsoranzo** [comment]
Ping. This is breaking the usual dependency update process for Galaxy.

**Comment by nsoranzo** [comment]
Thanks a lot @proccaserra ! If you could also create a new PyPI release with the fix when you have a minute, that would be fantastic!

**Comment by proccaserra** [comment]
@nsoranzo working on it, sorry for the delay on this one.  All the best :)

**Comment by nsoranzo** [comment]
Thank you! It wasn't a big issue until recently when some other required packages added incompatible pins, so no worries!

**Comment by nsoranzo** [comment]
@proccaserra Thanks for pushing the new release on PyPI! Unfortunately commit 3932fcbefea2aee2948317639554ee54038aeb3f reintroduced the problem of incompatible pins for Galaxy, do you actually need to specify the maximum version of six?
It is generally recommended to not use upper bound pins in Python libraries, if not necessary.

**Comment by proccaserra** [comment]
@nsoranzo, making another release now. @Zigur :)

**Comment by nsoranzo** [comment]
Thanks a lot for the help, all good now!

**Pull request merged**
